// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/openapi.yaml": {
            "get": {
                "description": "Returns the OpenAPI specification for this API in YAML format.",
                "produces": [
                    "application/x-yaml"
                ],
                "tags": [
                    "openapi"
                ],
                "summary": "Download OpenAPI spec",
                "responses": {
                    "200": {
                        "description": "OpenAPI spec in YAML format",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/currencies": {
            "get": {
                "description": "Returns all available currencies with their human-readable names and currency signs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Get currencies with names and signs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CurrenciesRecord"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            }
        },
        "/v1/rates/latest": {
            "get": {
                "description": "Get the latest currency exchange rates, optionally filtered by base currency and target symbols.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get latest exchange rates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base currency code (default: EUR)",
                        "name": "base",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of target currency symbols",
                        "name": "symbols",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ExchangeRateRecord"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            }
        },
        "/v1/rates/symbols": {
            "get": {
                "description": "Returns a list of all available currency symbols.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rates"
                ],
                "summary": "Get available currency symbols",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SymbolsRecord"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CurrenciesRecord": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.NamedSymbol"
                    }
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "handlers.ExchangeRateRecord": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "rates": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                }
            }
        },
        "handlers.NamedSymbol": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "sign": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "handlers.SymbolsRecord": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "symbols": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "utils.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Forex API",
	Description:      "API for fetching currency exchange rates.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
