name: CI

on:
    push:

env:
    PNPM_VERSION: 10.23.0
    SWAG_VERSION: v1.16.6

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Test
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Git - Checkout
              uses: actions/checkout@v6

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: go.mod
                  cache: true

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: pnpm

            - name: Install dependencies
              run: go mod download

            - name: Install pnpm dependencies
              run: pnpm install

            - name: Install swag
              run: go install github.com/swaggo/swag/cmd/swag@${{ env.SWAG_VERSION }}

            - name: Check OpenAPI docs are up to date
              run: |
                  swag init -g main.go --parseDependency --parseInternal
                  git diff --exit-code docs/

            - name: Run tests
              run: pnpm run test:all
